package thread;

public class TortoiseHareRace2 {

    public static void main(String[] args) {

        Tortoise tortoise = new Tortoise(10);
        Hare hare = new Hare(10);
        Thread tortoiseThread = new Thread(tortoise);
        Thread hareThread = new Thread(hare);
        tortoiseThread.start();
        hareThread.start();
    }
}

//one of results:

//tortoise has run  1 steps ... 
//tortoise has run  2 steps ... 
//tortoise has run  3 steps ... 
//tortoise has run  4 steps ... 
//tortoise has run  5 steps ... 
//hare has run 2 steps ... 
//hare has run 4 steps ... 
//hare has run 6 steps ... 
//Hare is sleeping ...
//hare has run 8 steps ... 
//tortoise has run  6 steps ... 
//tortoise has run  7 steps ... 
//tortoise has run  8 steps ... 
//tortoise has run  9 steps ... 
//tortoise has run  10 steps ... 
//hare has run 10 steps ... 